//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  /** Internal type. DO NOT USE DIRECTLY. */
type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
/** Internal type. DO NOT USE DIRECTLY. */
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  homepage: Homepage;
  homepageConnection: HomepageConnection;
  work: Work;
  workConnection: WorkConnection;
  faq: Faq;
  faqConnection: FaqConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHomepageArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHomepageConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomepageFilter>;
};


export type QueryWorkArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryWorkConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<WorkFilter>;
};


export type QueryFaqArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryFaqConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<FaqFilter>;
};

export type DocumentFilter = {
  homepage?: InputMaybe<HomepageFilter>;
  work?: InputMaybe<WorkFilter>;
  faq?: InputMaybe<FaqFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Homepage | Work | Faq | Folder;

export type HomepageHero = {
  __typename?: 'HomepageHero';
  badge?: Maybe<Scalars['String']['output']>;
  headline?: Maybe<Scalars['String']['output']>;
  headlineAccent?: Maybe<Scalars['String']['output']>;
  subtitle?: Maybe<Scalars['String']['output']>;
  ctaPrimary?: Maybe<Scalars['String']['output']>;
  ctaSecondary?: Maybe<Scalars['String']['output']>;
};

export type HomepageProblemCards = {
  __typename?: 'HomepageProblemCards';
  label?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  copy?: Maybe<Scalars['String']['output']>;
};

export type HomepageProblem = {
  __typename?: 'HomepageProblem';
  headline?: Maybe<Scalars['String']['output']>;
  subtitle?: Maybe<Scalars['String']['output']>;
  cards?: Maybe<Array<Maybe<HomepageProblemCards>>>;
};

export type HomepageCta = {
  __typename?: 'HomepageCta';
  title?: Maybe<Scalars['String']['output']>;
  copy?: Maybe<Scalars['String']['output']>;
  button?: Maybe<Scalars['String']['output']>;
};

export type Homepage = Node & Document & {
  __typename?: 'Homepage';
  hero?: Maybe<HomepageHero>;
  problem?: Maybe<HomepageProblem>;
  cta?: Maybe<HomepageCta>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type HomepageHeroFilter = {
  badge?: InputMaybe<StringFilter>;
  headline?: InputMaybe<StringFilter>;
  headlineAccent?: InputMaybe<StringFilter>;
  subtitle?: InputMaybe<StringFilter>;
  ctaPrimary?: InputMaybe<StringFilter>;
  ctaSecondary?: InputMaybe<StringFilter>;
};

export type HomepageProblemCardsFilter = {
  label?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  copy?: InputMaybe<StringFilter>;
};

export type HomepageProblemFilter = {
  headline?: InputMaybe<StringFilter>;
  subtitle?: InputMaybe<StringFilter>;
  cards?: InputMaybe<HomepageProblemCardsFilter>;
};

export type HomepageCtaFilter = {
  title?: InputMaybe<StringFilter>;
  copy?: InputMaybe<StringFilter>;
  button?: InputMaybe<StringFilter>;
};

export type HomepageFilter = {
  hero?: InputMaybe<HomepageHeroFilter>;
  problem?: InputMaybe<HomepageProblemFilter>;
  cta?: InputMaybe<HomepageCtaFilter>;
};

export type HomepageConnectionEdges = {
  __typename?: 'HomepageConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Homepage>;
};

export type HomepageConnection = Connection & {
  __typename?: 'HomepageConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<HomepageConnectionEdges>>>;
};

export type Work = Node & Document & {
  __typename?: 'Work';
  title?: Maybe<Scalars['String']['output']>;
  category?: Maybe<Scalars['String']['output']>;
  tags?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  image?: Maybe<Scalars['String']['output']>;
  problem?: Maybe<Scalars['String']['output']>;
  solution?: Maybe<Scalars['String']['output']>;
  outcome?: Maybe<Scalars['String']['output']>;
  order?: Maybe<Scalars['Float']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type NumberFilter = {
  lt?: InputMaybe<Scalars['Float']['input']>;
  lte?: InputMaybe<Scalars['Float']['input']>;
  gte?: InputMaybe<Scalars['Float']['input']>;
  gt?: InputMaybe<Scalars['Float']['input']>;
  eq?: InputMaybe<Scalars['Float']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['Float']['input']>>>;
};

export type WorkFilter = {
  title?: InputMaybe<StringFilter>;
  category?: InputMaybe<StringFilter>;
  tags?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  problem?: InputMaybe<StringFilter>;
  solution?: InputMaybe<StringFilter>;
  outcome?: InputMaybe<StringFilter>;
  order?: InputMaybe<NumberFilter>;
};

export type WorkConnectionEdges = {
  __typename?: 'WorkConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Work>;
};

export type WorkConnection = Connection & {
  __typename?: 'WorkConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<WorkConnectionEdges>>>;
};

export type Faq = Node & Document & {
  __typename?: 'Faq';
  question?: Maybe<Scalars['String']['output']>;
  answer?: Maybe<Scalars['String']['output']>;
  order?: Maybe<Scalars['Float']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type FaqFilter = {
  question?: InputMaybe<StringFilter>;
  answer?: InputMaybe<StringFilter>;
  order?: InputMaybe<NumberFilter>;
};

export type FaqConnectionEdges = {
  __typename?: 'FaqConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Faq>;
};

export type FaqConnection = Connection & {
  __typename?: 'FaqConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<FaqConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateHomepage: Homepage;
  createHomepage: Homepage;
  updateWork: Work;
  createWork: Work;
  updateFaq: Faq;
  createFaq: Faq;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateHomepageArgs = {
  relativePath: Scalars['String']['input'];
  params: HomepageMutation;
};


export type MutationCreateHomepageArgs = {
  relativePath: Scalars['String']['input'];
  params: HomepageMutation;
};


export type MutationUpdateWorkArgs = {
  relativePath: Scalars['String']['input'];
  params: WorkMutation;
};


export type MutationCreateWorkArgs = {
  relativePath: Scalars['String']['input'];
  params: WorkMutation;
};


export type MutationUpdateFaqArgs = {
  relativePath: Scalars['String']['input'];
  params: FaqMutation;
};


export type MutationCreateFaqArgs = {
  relativePath: Scalars['String']['input'];
  params: FaqMutation;
};

export type DocumentUpdateMutation = {
  homepage?: InputMaybe<HomepageMutation>;
  work?: InputMaybe<WorkMutation>;
  faq?: InputMaybe<FaqMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  homepage?: InputMaybe<HomepageMutation>;
  work?: InputMaybe<WorkMutation>;
  faq?: InputMaybe<FaqMutation>;
};

export type HomepageHeroMutation = {
  badge?: InputMaybe<Scalars['String']['input']>;
  headline?: InputMaybe<Scalars['String']['input']>;
  headlineAccent?: InputMaybe<Scalars['String']['input']>;
  subtitle?: InputMaybe<Scalars['String']['input']>;
  ctaPrimary?: InputMaybe<Scalars['String']['input']>;
  ctaSecondary?: InputMaybe<Scalars['String']['input']>;
};

export type HomepageProblemCardsMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  copy?: InputMaybe<Scalars['String']['input']>;
};

export type HomepageProblemMutation = {
  headline?: InputMaybe<Scalars['String']['input']>;
  subtitle?: InputMaybe<Scalars['String']['input']>;
  cards?: InputMaybe<Array<InputMaybe<HomepageProblemCardsMutation>>>;
};

export type HomepageCtaMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  copy?: InputMaybe<Scalars['String']['input']>;
  button?: InputMaybe<Scalars['String']['input']>;
};

export type HomepageMutation = {
  hero?: InputMaybe<HomepageHeroMutation>;
  problem?: InputMaybe<HomepageProblemMutation>;
  cta?: InputMaybe<HomepageCtaMutation>;
};

export type WorkMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  category?: InputMaybe<Scalars['String']['input']>;
  tags?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  image?: InputMaybe<Scalars['String']['input']>;
  problem?: InputMaybe<Scalars['String']['input']>;
  solution?: InputMaybe<Scalars['String']['input']>;
  outcome?: InputMaybe<Scalars['String']['input']>;
  order?: InputMaybe<Scalars['Float']['input']>;
};

export type FaqMutation = {
  question?: InputMaybe<Scalars['String']['input']>;
  answer?: InputMaybe<Scalars['String']['input']>;
  order?: InputMaybe<Scalars['Float']['input']>;
};

export type StringFilter = {
  startsWith?: string | null | undefined;
  eq?: string | null | undefined;
  exists?: boolean | null | undefined;
  in?: Array<string | null | undefined> | null | undefined;
};

export type HomepageHeroFilter = {
  badge?: StringFilter | null | undefined;
  headline?: StringFilter | null | undefined;
  headlineAccent?: StringFilter | null | undefined;
  subtitle?: StringFilter | null | undefined;
  ctaPrimary?: StringFilter | null | undefined;
  ctaSecondary?: StringFilter | null | undefined;
};

export type HomepageProblemCardsFilter = {
  label?: StringFilter | null | undefined;
  title?: StringFilter | null | undefined;
  copy?: StringFilter | null | undefined;
};

export type HomepageProblemFilter = {
  headline?: StringFilter | null | undefined;
  subtitle?: StringFilter | null | undefined;
  cards?: HomepageProblemCardsFilter | null | undefined;
};

export type HomepageCtaFilter = {
  title?: StringFilter | null | undefined;
  copy?: StringFilter | null | undefined;
  button?: StringFilter | null | undefined;
};

export type HomepageFilter = {
  hero?: HomepageHeroFilter | null | undefined;
  problem?: HomepageProblemFilter | null | undefined;
  cta?: HomepageCtaFilter | null | undefined;
};

export type ImageFilter = {
  startsWith?: string | null | undefined;
  eq?: string | null | undefined;
  exists?: boolean | null | undefined;
  in?: Array<string | null | undefined> | null | undefined;
};

export type NumberFilter = {
  lt?: number | null | undefined;
  lte?: number | null | undefined;
  gte?: number | null | undefined;
  gt?: number | null | undefined;
  eq?: number | null | undefined;
  exists?: boolean | null | undefined;
  in?: Array<number | null | undefined> | null | undefined;
};

export type WorkFilter = {
  title?: StringFilter | null | undefined;
  category?: StringFilter | null | undefined;
  tags?: StringFilter | null | undefined;
  image?: ImageFilter | null | undefined;
  problem?: StringFilter | null | undefined;
  solution?: StringFilter | null | undefined;
  outcome?: StringFilter | null | undefined;
  order?: NumberFilter | null | undefined;
};

export type FaqFilter = {
  question?: StringFilter | null | undefined;
  answer?: StringFilter | null | undefined;
  order?: NumberFilter | null | undefined;
};

export type HomepagePartsFragment = { __typename: 'Homepage', hero: { __typename: 'HomepageHero', badge: string | null, headline: string | null, headlineAccent: string | null, subtitle: string | null, ctaPrimary: string | null, ctaSecondary: string | null } | null, problem: { __typename: 'HomepageProblem', headline: string | null, subtitle: string | null, cards: Array<{ __typename: 'HomepageProblemCards', label: string | null, title: string | null, copy: string | null } | null> | null } | null, cta: { __typename: 'HomepageCta', title: string | null, copy: string | null, button: string | null } | null };

export type WorkPartsFragment = { __typename: 'Work', title: string | null, category: string | null, tags: Array<string | null> | null, image: string | null, problem: string | null, solution: string | null, outcome: string | null, order: number | null };

export type FaqPartsFragment = { __typename: 'Faq', question: string | null, answer: string | null, order: number | null };

export type HomepageQueryVariables = Exact<{
  relativePath: string;
}>;


export type HomepageQuery = { homepage: { __typename: 'Homepage', id: string, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero: { __typename: 'HomepageHero', badge: string | null, headline: string | null, headlineAccent: string | null, subtitle: string | null, ctaPrimary: string | null, ctaSecondary: string | null } | null, problem: { __typename: 'HomepageProblem', headline: string | null, subtitle: string | null, cards: Array<{ __typename: 'HomepageProblemCards', label: string | null, title: string | null, copy: string | null } | null> | null } | null, cta: { __typename: 'HomepageCta', title: string | null, copy: string | null, button: string | null } | null } };

export type HomepageConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: HomepageFilter | null | undefined;
}>;


export type HomepageConnectionQuery = { homepageConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'Homepage', id: string, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero: { __typename: 'HomepageHero', badge: string | null, headline: string | null, headlineAccent: string | null, subtitle: string | null, ctaPrimary: string | null, ctaSecondary: string | null } | null, problem: { __typename: 'HomepageProblem', headline: string | null, subtitle: string | null, cards: Array<{ __typename: 'HomepageProblemCards', label: string | null, title: string | null, copy: string | null } | null> | null } | null, cta: { __typename: 'HomepageCta', title: string | null, copy: string | null, button: string | null } | null } | null } | null> | null } };

export type WorkQueryVariables = Exact<{
  relativePath: string;
}>;


export type WorkQuery = { work: { __typename: 'Work', id: string, title: string | null, category: string | null, tags: Array<string | null> | null, image: string | null, problem: string | null, solution: string | null, outcome: string | null, order: number | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type WorkConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: WorkFilter | null | undefined;
}>;


export type WorkConnectionQuery = { workConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'Work', id: string, title: string | null, category: string | null, tags: Array<string | null> | null, image: string | null, problem: string | null, solution: string | null, outcome: string | null, order: number | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type FaqQueryVariables = Exact<{
  relativePath: string;
}>;


export type FaqQuery = { faq: { __typename: 'Faq', id: string, question: string | null, answer: string | null, order: number | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type FaqConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: FaqFilter | null | undefined;
}>;


export type FaqConnectionQuery = { faqConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'Faq', id: string, question: string | null, answer: string | null, order: number | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export const HomepagePartsFragmentDoc = gql`
    fragment HomepageParts on Homepage {
  __typename
  hero {
    __typename
    badge
    headline
    headlineAccent
    subtitle
    ctaPrimary
    ctaSecondary
  }
  problem {
    __typename
    headline
    subtitle
    cards {
      __typename
      label
      title
      copy
    }
  }
  cta {
    __typename
    title
    copy
    button
  }
}
    `;
export const WorkPartsFragmentDoc = gql`
    fragment WorkParts on Work {
  __typename
  title
  category
  tags
  image
  problem
  solution
  outcome
  order
}
    `;
export const FaqPartsFragmentDoc = gql`
    fragment FaqParts on Faq {
  __typename
  question
  answer
  order
}
    `;
export const HomepageDocument = gql`
    query homepage($relativePath: String!) {
  homepage(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...HomepageParts
  }
}
    ${HomepagePartsFragmentDoc}`;
export const HomepageConnectionDocument = gql`
    query homepageConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: HomepageFilter) {
  homepageConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...HomepageParts
      }
    }
  }
}
    ${HomepagePartsFragmentDoc}`;
export const WorkDocument = gql`
    query work($relativePath: String!) {
  work(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...WorkParts
  }
}
    ${WorkPartsFragmentDoc}`;
export const WorkConnectionDocument = gql`
    query workConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: WorkFilter) {
  workConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...WorkParts
      }
    }
  }
}
    ${WorkPartsFragmentDoc}`;
export const FaqDocument = gql`
    query faq($relativePath: String!) {
  faq(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...FaqParts
  }
}
    ${FaqPartsFragmentDoc}`;
export const FaqConnectionDocument = gql`
    query faqConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: FaqFilter) {
  faqConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...FaqParts
      }
    }
  }
}
    ${FaqPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      homepage(variables: HomepageQueryVariables, options?: C): Promise<{data: HomepageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomepageQueryVariables, query: string}> {
        return requester<{data: HomepageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomepageQueryVariables, query: string}, HomepageQueryVariables>(HomepageDocument, variables, options);
      },
    homepageConnection(variables?: HomepageConnectionQueryVariables, options?: C): Promise<{data: HomepageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomepageConnectionQueryVariables, query: string}> {
        return requester<{data: HomepageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomepageConnectionQueryVariables, query: string}, HomepageConnectionQueryVariables>(HomepageConnectionDocument, variables, options);
      },
    work(variables: WorkQueryVariables, options?: C): Promise<{data: WorkQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: WorkQueryVariables, query: string}> {
        return requester<{data: WorkQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: WorkQueryVariables, query: string}, WorkQueryVariables>(WorkDocument, variables, options);
      },
    workConnection(variables?: WorkConnectionQueryVariables, options?: C): Promise<{data: WorkConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: WorkConnectionQueryVariables, query: string}> {
        return requester<{data: WorkConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: WorkConnectionQueryVariables, query: string}, WorkConnectionQueryVariables>(WorkConnectionDocument, variables, options);
      },
    faq(variables: FaqQueryVariables, options?: C): Promise<{data: FaqQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FaqQueryVariables, query: string}> {
        return requester<{data: FaqQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FaqQueryVariables, query: string}, FaqQueryVariables>(FaqDocument, variables, options);
      },
    faqConnection(variables?: FaqConnectionQueryVariables, options?: C): Promise<{data: FaqConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FaqConnectionQueryVariables, query: string}> {
        return requester<{data: FaqConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FaqConnectionQueryVariables, query: string}, FaqConnectionQueryVariables>(FaqConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "https://content.tinajs.io/2.4/content/3c766213-b1a1-4b9b-814d-37d2acb5f95f/github/main",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

export type { Exact };

  